- name: Create flavor, image, keypair, network, and security groups in OSP 
  hosts: workstation
  become: yes
  roles:
    - osp-setup

- name: Create instances for three-tier-app
  hosts: workstation
  become: yes
  roles:
    - osp-servers
