- name: Create flavor, image, keypair, network, and security groups in OSP 
  hosts: localhost
  gather_facts: false
  #hosts: workstation
  become: yes
  roles:
    - osp-setup

- name: Create instances for three-tier-app
  hosts: localhost
  gather_facts: false
  #hosts: workstation
  become: yes
  roles:
    - osp-servers
