---
- name: Create flavor, image, keypair, network, and security groups in OSP
  hosts: localhost
  # hosts: workstation
  gather_facts: false
  become: false
  # become: true
  roles:
    - osp-setup

- name: Create instances for three-tier-app
  hosts: localhost
  # hosts: workstation
  gather_facts: false
  become: false
  # become: true
  roles:
    - osp-servers
