---
# Set up workstation, create osp network, router, SG, ssh keypair

- name: Set up workstation - Create inventory
  hosts: localhost
  tasks:
  - name: Create workstation inventory
    add_host:
       name: "workstation-{{OSP_GUID}}.rhpds.opentlc.com"
       group: workstation

- name: Create osp network, router, SG and ssh keypair - Run setup
  hosts: workstation
  become: true
  roles:
    - setup-workstation

- import_playbook: site-install-isolated-node.yml
