---
- name: AWS smoke test
  hosts: frontends
  gather_facts: false
  tasks:
    - name: Query three-tier frontend website to test availability
      uri:
        url: "http://{{ inventory_hostname }}/"
        return_content: true
      register: webpage

    - name: DEBUG - webpage var
      debug:
        var: webpage
        verbosity: 1

    - name: Fail if 'Ansible has done its job' is not in the page content
      fail:
      when: "'Ansible has done its job' not in webpage.content"
