---
# tasks file for lb-tier
# httpie does not seem to be in common repos
- name: install HAProxy
  yum:
    name:
    - haproxy
    # - httpie
    state: present

- name: configure haproxy for OSP
  template:
    src: ./haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart HAproxy
  when:
    - hostvars[inventory_hostname]['ansible_host'] is undefined

- name: DEBUG for AWS
  debug: 
    var: hostvars[inventory_hostname]['ansible_default_ipv4']['address']
    verbosity: 1

- name: configure haproxy for AWS
  template:
    src: ./haproxyaws.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart HAproxy
  when:
    - hostvars[inventory_hostname]['ansible_host'] is defined
    - hostvars[inventory_hostname]['ansible_host'] == "18.204.126.255"
