---
# handlers file for app-tier
- name: restart apache
  service:
    name: httpd
    enabled: yes
    state: restarted

- name: start tomcat
  service:
    name: tomcat
    state: started
    enabled: yes
