---
# tasks file for app-tier
- name: install apache
  yum:
    name: httpd
    state: present

- name: create ansible folder inside tomcat folder
  file:
    path: "{{ apache_web_dir }}"
    state: directory

- name: copy static index.html to {{ apache_web_dir }}
  template:
    src: index.html.j2
    dest: "{{ apache_web_dir }}/index.html"

- name: install tomcat
  package:
    name: tomcat
    state: present

- name: create ansible tomcat directory
  file:
    path: "{{ tomcat_web_dir }}"
    state: directory

- name: copy static index.html to tomcat webapps/ansible/index.html
  template:
    src: index.html.j2
    dest: "{{ tomcat_web_dir }}/index.html"
    mode: 0644
  notify: start tomcat
