---
# tasks file for base-config
- name: enable repos
  copy:
    src: internal.repo
    dest: /etc/yum.repos.d/internal.repo
    mode: 0644

- name: update yum cache (returned error without)
  command: yum clean all

- name: update yum cache (returned error without)
  command: yum makecache
